platform :ios, ‘9.0’
inhibit_all_warnings!
target 'CRHelperLib’ do
  pod 'MJRefresh'
  pod 'AFNetworking', '~> 3.2.1'
  pod 'SDWebImage', '~> 4.4.6'
  pod 'Masonry', '~> 1.1.0'
  # Pods for testing
end


